version: '2'
services:
  r8meuserservice2-app:
    image: r8meuserservice2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://r8meuserservice2-postgresql:5432/r8meuserservice2'
      - 'JHIPSTER_CACHE_REDIS_SERVER=redis://r8meuserservice2-redis:6379'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://r8meuserservice2-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://r8meuserservice2-elasticsearch:9200'
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
      - JHIPSTER_METRICS_LOGS_ENABLED=true
      - JHIPSTER_METRICS_LOGS_REPORT_FREQUENCY=60
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'
  r8meuserservice2-postgresql:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=r8meuserservice2
      - POSTGRES_PASSWORD=
  r8meuserservice2-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node
  r8meuserservice2-redis:
    image: 'redis:5.0.6'

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
