version: '2'
services:
  r8meuserservice2-app:
    image: r8meuserservice2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://r8meuserservice2-postgresql:5432/r8meuserservice2
      - JHIPSTER_CACHE_REDIS_SERVER=redis://r8meuserservice2-redis:6379
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://r8meuserservice2-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://r8meuserservice2-elasticsearch:9200
    ports:
      - 8080:8080
  r8meuserservice2-postgresql:
    extends:
      file: postgresql.yml
      service: r8meuserservice2-postgresql
  r8meuserservice2-redis:
    extends:
      file: redis.yml
      service: r8meuserservice2-redis
  r8meuserservice2-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: r8meuserservice2-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
